apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examen
  template:
    metadata:
      labels:
        app: examen
    spec:
      containers:
      - name: examen
        image: examen:latest
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: examen-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
  selector:
    app: examen
